# Generated by Django 5.0.4 on 2024-04-16 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('info', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_debt_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_debt_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_debt_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_debt_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unpaid_debt_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unpaid_debt_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='store_store_created_da4b58_idx')],
            },
        ),
    ]
