# Generated by Django 5.0.4 on 2024-05-30 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_paid_debt_usd_alter_store_paid_debt_uzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
